### ISSUE TITLE
Guzzle fails to send headers and requests to incorrect URL

### ISSUE THREAD

**Issue by jarrodbell** [JayBizzle/DeployBot-API#6]
Using Guzzle 6.3.3, the headers fail to send.

I resolved by using my own Guzzle Client in the constructor like so:

```php
$dbot = new DeployBot($this->settings['deploybot']['key'], $this->settings['deploybot']['user'],
	new Client([
		'base_uri' => "https://" . $this->settings['deploybot']['user'] . ".deploybot.com/api/v1/",
		'headers'  => [
			'X-Api-Token' => $this->settings['deploybot']['key'],
			'Accept'      => 'application/json',
		]
	])
);
```

Notice use of `base_uri` instead of `base_url` and moving the headers up to the root element (no `defaults`) needed.

**Comment by JayBizzle** [comment]
Thanks for reporting.

Just tested this and I am also seeing the same issue. Not sure what has changed on the Guzzle end recently to cause this issue.

Would you be willing to create a PR to fix this? Otherwise, I may get some time next week to look into fixing it.

Thanks 👍

**Comment by jarrodbell** [comment]
Done see #7
